name: Deploy React WebApps.

on:
  pull_request:
    paths:
      - "examples/Web Applications/Framework Examples/**"
      - ".github/workflows/webapp-deploy.yml"

  push:
    branches:
      - "**"
    paths:
      - "examples/Web Applications/Framework Examples/**"
      - ".github/workflows/webapp-deploy.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-package-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix: # Add  frameworks and Folder names here
        include:
          - framework: React
            app-folder: ApiKeyAuthApp
          # - framework: Angular
          #   app-folder:    # example entry
          # - framework: Blazor
          #   app-folder:    # example entry

    env:
      NODE_VERSION: "24.x"
      DOTNET_VERSION: "8.0"
      REACT_APPS_DIR: "examples/Web Applications/Framework Examples/React"
      ANGULAR_APPS_DIR: "examples/Web Applications/Framework Examples/Angular"
      BLAZOR_APPS_DIR: "examples/Web Applications/Framework Examples/Blazor"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set App Directory
        run: |
          declare -A DIRS
          DIRS=( ["React"]="${{ env.REACT_APPS_DIR }}" ["Angular"]="${{ env.ANGULAR_APPS_DIR }}" ["Blazor"]="${{ env.BLAZOR_APPS_DIR }}" )
          if [[ -v DIRS[${{ matrix.framework }}] ]]; then
            echo "APP_DIR=${DIRS[${{ matrix.framework }}]}/${{ matrix.app-folder }}" >> $GITHUB_ENV
          else
            echo "Unsupported framework: ${{ matrix.framework }}"
            exit 1
          fi

      - name: Setup Node.js
        if: matrix.framework != 'Blazor'
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup .NET SDK
        if: matrix.framework == 'Blazor'
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install dependencies
        working-directory: ${{ env.APP_DIR }}
        run: |
          if [ "${{ matrix.framework }}" = "Blazor" ]; then
            dotnet restore
          else
            npm ci
          fi

      - name: Lint (javascript/typescript apps only)
        working-directory: ${{ env.APP_DIR }}
        run: |
          if [ "${{ matrix.framework }}" != "Blazor" ]; then
            npm run lint
          else
            echo "Skipping lint for Blazor"
          fi

      - name: Build
        working-directory: ${{ env.APP_DIR }}
        run: |
          if [ "${{ matrix.framework }}" = "Blazor" ]; then
            dotnet build --configuration Release
          else
            npm run build
          fi

      - name: Setup Homebrew + Install slcli
        if:
          github.repository_owner == 'ni' && startsWith(github.ref,
          'refs/heads/main')
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew tap ni-kismet/homebrew-ni
          brew install slcli
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Package into .nipkg
        if:
          github.repository_owner == 'ni' && startsWith(github.ref,
          'refs/heads/main')
        working-directory: ${{ env.APP_DIR }}
        run: |
          WEBAPP_NAME=$(basename "$PWD")
          slcli webapp pack dist/ --output "${WEBAPP_NAME}.nipkg"
          echo "WEBAPP_NAME=${WEBAPP_NAME}" >> $GITHUB_ENV

      - name: Upload .nipkg artifact to gitHub
        if:
          github.repository_owner == 'ni' && startsWith(github.ref,
          'refs/heads/main')
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.app-folder }}.nipkg
          path: ${{env.REACT_APPS_DIR}}/${{matrix.app-folder}}/${{env.WEBAPP_NAME}}.nipkg

      - name: Login to SystemLink
        if:
          github.repository_owner == 'ni' && startsWith(github.ref,
          'refs/heads/main')
        run: |
          slcli login --profile ghActions --url "${{ secrets.SL_API_URL }}" --api-key "${{ secrets.SL_API_KEY }}" --web-url "${{ secrets.SL_WEBSITE_URL }}" --workspace "${{secrets.SL_WORKSPACE}}"

      - name:
          Deploy (publish new/update) webapp (nipkg) to NI internal SystemLink
          test tier
        if:
          github.repository_owner == 'ni' && startsWith(github.ref,
          'refs/heads/main')
        working-directory: ${{ env.APP_DIR }}
        run: |
          pkg=${{env.WEBAPP_NAME}}.nipkg
          WEBAPP_NAME="$(basename "$pkg" .nipkg)_PROD"
          echo "**Deploying "$pkg" "$WEBAPP_NAME"**"
          WEBAPP_ID=$(slcli webapp list --workspace "${{ secrets.SL_WORKSPACE }}" --filter "$WEBAPP_NAME" --format json | jq -r '.[0].id // empty')
          if [[ -z "$WEBAPP_ID" ]]; then
            echo "   *Webapp does not exist -- publishing new"
            slcli webapp publish "$pkg" --name "$WEBAPP_NAME" --workspace "${{ secrets.SL_WORKSPACE }}"
          else
            echo "  *Webapp exists -- updating"
            slcli webapp publish "$pkg" --id "$WEBAPP_ID"
          fi
          echo "**Deployed "$WEBAPP_NAME"**"
